# Generated by Django 6.0.3 on 2026-03-21 19:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('league', models.CharField(choices=[('ipl', 'IPL'), ('psl', 'PSL')], max_length=8)),
                ('status', models.CharField(choices=[('setup', 'Setup'), ('running', 'Running'), ('finished', 'Finished')], default='setup', max_length=16)),
                ('current_player_index', models.IntegerField(default=0)),
                ('current_bid_lakhs', models.IntegerField(default=0)),
                ('lot_ends_at', models.DateTimeField(blank=True, null=True)),
                ('last_autobid_at', models.DateTimeField(blank=True, null=True)),
                ('round_number', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuctionTeam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('short_code', models.CharField(blank=True, default='', max_length=8)),
                ('is_user', models.BooleanField(default=False)),
                ('strategy', models.CharField(choices=[('aggressive', 'Aggressive'), ('balanced', 'Balanced'), ('defensive', 'Defensive')], default='balanced', max_length=16)),
                ('category_interest', models.JSONField(blank=True, default=dict)),
                ('budget_lakhs', models.IntegerField(default=6000)),
                ('squad_count', models.PositiveSmallIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='auction.auctionsession')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('session', 'name')},
            },
        ),
        migrations.AddField(
            model_name='auctionsession',
            name='highest_bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leading_lots', to='auction.auctionteam'),
        ),
        migrations.AddField(
            model_name='auctionsession',
            name='user_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_sessions', to='auction.auctionteam'),
        ),
        migrations.CreateModel(
            name='AuctionPlayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('base_price_lakhs', models.IntegerField()),
                ('category', models.CharField(choices=[('Batsman', 'Batsman'), ('Bowler', 'Bowler'), ('All-rounder', 'All-rounder'), ('WK', 'WK')], max_length=16)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sold', 'Sold'), ('unsold', 'Unsold')], default='pending', max_length=16)),
                ('sold_price_lakhs', models.IntegerField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='auction.auctionsession')),
                ('sold_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='auction.auctionteam')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='AuctionBidLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount_lakhs', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.auctionplayer')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_logs', to='auction.auctionsession')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.auctionteam')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
