# Generated by Django 6.0.3 on 2026-03-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionsession',
            name='status',
            field=models.CharField(choices=[('setup', 'Setup'), ('running', 'Running'), ('paused', 'Paused'), ('finished', 'Finished')], default='setup', max_length=16),
        ),
    ]
