# Generated by Django 6.0.2 on 2026-03-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('team_home', models.CharField(max_length=100)),
                ('team_away', models.CharField(max_length=100)),
                ('series_name', models.CharField(blank=True, default='', max_length=200)),
                ('venue', models.CharField(blank=True, default='', max_length=200)),
                ('start_time_utc', models.DateTimeField()),
                ('status', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'ordering': ['start_time_utc'],
            },
        ),
    ]
