# Generated by Django 6.0.2 on 2026-03-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllRounderRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('format_type', models.CharField(choices=[('odi', 'ODI'), ('t20', 'T20'), ('test', 'Test')], max_length=10)),
                ('rank', models.PositiveIntegerField()),
                ('rating', models.PositiveIntegerField()),
                ('career_best_rating', models.PositiveIntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['format_type', 'rank'],
                'unique_together': {('player_name', 'format_type')},
            },
        ),
        migrations.CreateModel(
            name='BatterRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('format_type', models.CharField(choices=[('odi', 'ODI'), ('t20', 'T20'), ('test', 'Test')], max_length=10)),
                ('rank', models.PositiveIntegerField()),
                ('rating', models.PositiveIntegerField()),
                ('career_best_rating', models.PositiveIntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['format_type', 'rank'],
                'unique_together': {('player_name', 'format_type')},
            },
        ),
        migrations.CreateModel(
            name='BowlerRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('format_type', models.CharField(choices=[('odi', 'ODI'), ('t20', 'T20'), ('test', 'Test')], max_length=10)),
                ('rank', models.PositiveIntegerField()),
                ('rating', models.PositiveIntegerField()),
                ('career_best_rating', models.PositiveIntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['format_type', 'rank'],
                'unique_together': {('player_name', 'format_type')},
            },
        ),
        migrations.CreateModel(
            name='TeamRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('team_code', models.CharField(max_length=10)),
                ('format_type', models.CharField(choices=[('odi', 'ODI'), ('t20', 'T20'), ('test', 'Test')], max_length=10)),
                ('rank', models.PositiveIntegerField()),
                ('rating', models.PositiveIntegerField()),
                ('flag_url', models.URLField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['format_type', 'rank'],
                'unique_together': {('team_name', 'format_type')},
            },
        ),
    ]
