# Generated by Django 6.0.2 on 2026-03-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamranking',
            name='flag_url',
        ),
        migrations.AlterField(
            model_name='allrounderranking',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='batterranking',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bowlerranking',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='teamranking',
            name='team_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
