# Generated by Django 6.0.2 on 2026-03-02 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_home', models.CharField(max_length=100)),
                ('team_away', models.CharField(max_length=100)),
                ('home_score', models.CharField(default='0', max_length=10)),
                ('away_score', models.CharField(default='0', max_length=10)),
                ('status', models.CharField(max_length=50)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='matches.series')),
            ],
        ),
    ]
