# Generated by Django 6.0.2 on 2026-03-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='external_id',
            field=models.CharField(default=0, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='name',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='external_id',
            field=models.CharField(default=0, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='away_score',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_score',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='series',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
