# Generated by Django 6.0.2 on 2026-03-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_external_id_match_name_series_external_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away_score',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_score',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
