# Generated by Django 6.0.2 on 2026-03-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_alter_match_away_score_alter_match_home_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='scorecard_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
