# Generated by Django 6.0.3 on 2026-03-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_team_squad_cache'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesStatsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_external_id', models.CharField(max_length=100, unique=True)),
                ('series_name', models.CharField(blank=True, default='', max_length=255)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TeamSquadCache',
        ),
    ]
