# Generated by Django 6.0.3 on 2026-03-20 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0010_seriesstatscache_delete_teamsquadcache'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchHighlightsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(blank=True, default='', max_length=255)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='highlights_cache', to='matches.match')),
            ],
        ),
    ]
