"""
IPL player pool for mini auction — names and roles (curated from IPL franchise squads).
Categories: Batsman, Bowler, All-rounder, WK (matches AuctionPlayer category choices).
"""
from __future__ import annotations

from .auction_engine import ALLOWED_BASE_PRICE_LAKHS
from .models import AuctionPlayer as P

# ₹2 Cr base for these marquee names (lakhs). Keys are lowercased for lookup.
IPL_STAR_BASE_PRICE_LAKHS: dict[str, int] = {
    "virat kohli": 200,
    "ms dhoni": 200,
    "jasprit bumrah": 200,
    "sanju samson": 200,
    "hardik pandya": 200,
    "ruturaj gaikwad": 200,
    "dewald brevis": 200,
    "shivam dube": 200,
    "rishabh pant": 200,
    "josh hazlewood": 200,
    "shreyas iyer": 200,
    "marco jansen": 200,
}


def resolve_ipl_base_price_lakhs(name: str) -> int:
    """Deterministic base from name; marquee players use fixed ₹2 Cr."""
    key = name.strip().lower()
    if key in IPL_STAR_BASE_PRICE_LAKHS:
        return IPL_STAR_BASE_PRICE_LAKHS[key]
    tiers = ALLOWED_BASE_PRICE_LAKHS
    return tiers[sum(ord(c) for c in name) % len(tiers)]


def get_ipl_player_rows() -> list[dict[str, str]]:
    """Return unique players as {name, category}."""
    raw: list[tuple[str, str]] = [
        # Mumbai Indians
        ("Rohit Sharma", P.CAT_BAT),
        ("Suryakumar Yadav", P.CAT_BAT),
        ("Tilak Varma", P.CAT_BAT),
        ("Tim David", P.CAT_BAT),
        ("Dewald Brevis", P.CAT_BAT),
        ("Nehal Wadhera", P.CAT_BAT),
        ("Vishnu Vinod", P.CAT_WK),
        ("Ishan Kishan", P.CAT_WK),
        ("Hardik Pandya", P.CAT_AR),
        ("Romario Shepherd", P.CAT_AR),
        ("Shams Mulani", P.CAT_AR),
        ("Mohammad Nabi", P.CAT_AR),
        ("Jasprit Bumrah", P.CAT_BOWL),
        ("Gerald Coetzee", P.CAT_BOWL),
        ("Piyush Chawla", P.CAT_BOWL),
        ("Jason Behrendorff", P.CAT_BOWL),
        ("Kumar Kartikeya", P.CAT_BOWL),
        ("Nuwan Thushara", P.CAT_BOWL),
        ("Arjun Tendulkar", P.CAT_BOWL),
        ("Shreyas Gopal", P.CAT_BOWL),
        ("Anshul Kamboj", P.CAT_BOWL),
        ("Mujeeb Ur Rahman", P.CAT_BOWL),
        ("Kwena Maphaka", P.CAT_BOWL),
        ("Naman Dhir", P.CAT_BAT),
        # Chennai Super Kings
        ("Ruturaj Gaikwad", P.CAT_BAT),
        ("Devon Conway", P.CAT_BAT),
        ("Ajinkya Rahane", P.CAT_BAT),
        ("Shivam Dube", P.CAT_BAT),
        ("MS Dhoni", P.CAT_WK),
        ("Sameer Rizvi", P.CAT_BAT),
        ("Shaik Rasheed", P.CAT_BAT),
        ("Ravindra Jadeja", P.CAT_AR),
        ("Daryl Mitchell", P.CAT_AR),
        ("Moeen Ali", P.CAT_AR),
        ("Deepak Chahar", P.CAT_BOWL),
        ("Tushar Deshpande", P.CAT_BOWL),
        ("Maheesh Theekshana", P.CAT_BOWL),
        ("Mitchell Santner", P.CAT_BOWL),
        ("Simarjeet Singh", P.CAT_BOWL),
        ("Matheesha Pathirana", P.CAT_BOWL),
        ("Mustafizur Rahman", P.CAT_BOWL),
        ("Shardul Thakur", P.CAT_BOWL),
        ("Rajvardhan Hangargekar", P.CAT_BOWL),
        ("Prashant Solanki", P.CAT_BOWL),
        ("Mukesh Choudhary", P.CAT_BOWL),
        ("Nishant Sindhu", P.CAT_AR),
        ("Rachin Ravindra", P.CAT_AR),
        # Royal Challengers Bengaluru
        ("Virat Kohli", P.CAT_BAT),
        ("Faf du Plessis", P.CAT_BAT),
        ("Glenn Maxwell", P.CAT_AR),
        ("Cameron Green", P.CAT_AR),
        ("Rajat Patidar", P.CAT_BAT),
        ("Dinesh Karthik", P.CAT_WK),
        ("Anuj Rawat", P.CAT_WK),
        ("Mahipal Lomror", P.CAT_BAT),
        ("Suyash Prabhudessai", P.CAT_BAT),
        ("Will Jacks", P.CAT_AR),
        ("Mohammed Siraj", P.CAT_BOWL),
        ("Josh Hazlewood", P.CAT_BOWL),
        ("Lockie Ferguson", P.CAT_BOWL),
        ("Yash Dayal", P.CAT_BOWL),
        ("Karn Sharma", P.CAT_BOWL),
        ("Akash Deep", P.CAT_BOWL),
        ("Vyshak Vijaykumar", P.CAT_BOWL),
        ("Swapnil Singh", P.CAT_BOWL),
        ("Reece Topley", P.CAT_BOWL),
        ("Tom Curran", P.CAT_AR),
        ("Alzarri Joseph", P.CAT_BOWL),
        ("Saurav Chauhan", P.CAT_BAT),
        # Kolkata Knight Riders
        ("Shreyas Iyer", P.CAT_BAT),
        ("Venkatesh Iyer", P.CAT_AR),
        ("Nitish Rana", P.CAT_BAT),
        ("Rinku Singh", P.CAT_BAT),
        ("Rahmanullah Gurbaz", P.CAT_WK),
        ("Phil Salt", P.CAT_WK),
        ("Sunil Narine", P.CAT_AR),
        ("Andre Russell", P.CAT_AR),
        ("Ramandeep Singh", P.CAT_BAT),
        ("Angkrish Raghuvanshi", P.CAT_BAT),
        ("Mitchell Starc", P.CAT_BOWL),
        ("Harshit Rana", P.CAT_BOWL),
        ("Varun Chakaravarthy", P.CAT_BOWL),
        ("Chetan Sakariya", P.CAT_BOWL),
        ("Vaibhav Arora", P.CAT_BOWL),
        ("Gus Atkinson", P.CAT_BOWL),
        ("Sakib Hussain", P.CAT_BOWL),
        ("Mujeeb Ur Rahman", P.CAT_BOWL),
        ("Sherfane Rutherford", P.CAT_BAT),
        ("Manish Pandey", P.CAT_BAT),
        ("Anukul Roy", P.CAT_AR),
        # Rajasthan Royals
        ("Sanju Samson", P.CAT_WK),
        ("Yashasvi Jaiswal", P.CAT_BAT),
        ("Jos Buttler", P.CAT_BAT),
        ("Shimron Hetmyer", P.CAT_BAT),
        ("Dhruv Jurel", P.CAT_WK),
        ("Riyan Parag", P.CAT_BAT),
        ("Rovman Powell", P.CAT_BAT),
        ("Nandre Burger", P.CAT_BOWL),
        ("Trent Boult", P.CAT_BOWL),
        ("Yuzvendra Chahal", P.CAT_BOWL),
        ("Ravichandran Ashwin", P.CAT_AR),
        ("Avesh Khan", P.CAT_BOWL),
        ("Kuldeep Sen", P.CAT_BOWL),
        ("Navdeep Saini", P.CAT_BOWL),
        ("Sandeep Sharma", P.CAT_BOWL),
        ("Adam Zampa", P.CAT_BOWL),
        ("Tanush Kotian", P.CAT_AR),
        ("Kunal Singh Rathore", P.CAT_BAT),
        ("Shubham Dubey", P.CAT_BAT),
        ("Abid Mushtaq", P.CAT_AR),
        ("Keshav Maharaj", P.CAT_BOWL),
        # Sunrisers Hyderabad
        ("Pat Cummins", P.CAT_AR),
        ("Travis Head", P.CAT_BAT),
        ("Abhishek Sharma", P.CAT_BAT),
        ("Heinrich Klaasen", P.CAT_WK),
        ("Aiden Markram", P.CAT_BAT),
        ("Rahul Tripathi", P.CAT_BAT),
        ("Abdul Samad", P.CAT_AR),
        ("Bhuvneshwar Kumar", P.CAT_BOWL),
        ("T Natarajan", P.CAT_BOWL),
        ("Umran Malik", P.CAT_BOWL),
        ("Washington Sundar", P.CAT_AR),
        ("Mayank Markande", P.CAT_BOWL),
        ("Jaydev Unadkat", P.CAT_BOWL),
        ("Fazalhaq Farooqi", P.CAT_BOWL),
        ("Marco Jansen", P.CAT_AR),
        ("Glenn Phillips", P.CAT_BAT),
        ("Anmolpreet Singh", P.CAT_BAT),
        ("Mayank Agarwal", P.CAT_BAT),
        ("Upendra Yadav", P.CAT_WK),
        ("Wanindu Hasaranga", P.CAT_AR),
        ("Shahbaz Ahmed", P.CAT_AR),
        ("Jhathavedh Subramanyan", P.CAT_BOWL),
        # Delhi Capitals
        ("Rishabh Pant", P.CAT_WK),
        ("David Warner", P.CAT_BAT),
        ("Prithvi Shaw", P.CAT_BAT),
        ("Mitchell Marsh", P.CAT_AR),
        ("Axar Patel", P.CAT_AR),
        ("Kuldeep Yadav", P.CAT_BOWL),
        ("Anrich Nortje", P.CAT_BOWL),
        ("Khaleel Ahmed", P.CAT_BOWL),
        ("Ishant Sharma", P.CAT_BOWL),
        ("Mukesh Kumar", P.CAT_BOWL),
        ("Lungi Ngidi", P.CAT_BOWL),
        ("Rasikh Dar", P.CAT_BOWL),
        ("Jhye Richardson", P.CAT_BOWL),
        ("Kumar Kushagra", P.CAT_WK),
        ("Yash Dhull", P.CAT_BAT),
        ("Swastik Chikara", P.CAT_BAT),
        ("Jake Fraser-McGurk", P.CAT_BAT),
        ("Tristan Stubbs", P.CAT_BAT),
        ("Sumit Kumar", P.CAT_AR),
        ("Vicky Ostwal", P.CAT_AR),
        ("Abishek Porel", P.CAT_WK),
        ("Shai Hope", P.CAT_BAT),
        # Punjab Kings
        ("Shikhar Dhawan", P.CAT_BAT),
        ("Jonny Bairstow", P.CAT_WK),
        ("Liam Livingstone", P.CAT_AR),
        ("Sam Curran", P.CAT_AR),
        ("Jitesh Sharma", P.CAT_WK),
        ("Prabhsimran Singh", P.CAT_WK),
        ("Rilee Rossouw", P.CAT_BAT),
        ("Harpreet Brar", P.CAT_AR),
        ("Kagiso Rabada", P.CAT_BOWL),
        ("Arshdeep Singh", P.CAT_BOWL),
        ("Rahul Chahar", P.CAT_BOWL),
        ("Harshal Patel", P.CAT_BOWL),
        ("Nathan Ellis", P.CAT_BOWL),
        ("Vidwath Kaverappa", P.CAT_BOWL),
        ("Shivam Singh", P.CAT_BAT),
        ("Ashutosh Sharma", P.CAT_BAT),
        ("Chris Woakes", P.CAT_AR),
        ("Prince Choudhary", P.CAT_BOWL),
        ("Tanay Thyagarajan", P.CAT_AR),
        ("Vishwanath Singh", P.CAT_AR),
        # Lucknow Super Giants
        ("KL Rahul", P.CAT_BAT),
        ("Quinton de Kock", P.CAT_WK),
        ("Nicholas Pooran", P.CAT_BAT),
        ("Marcus Stoinis", P.CAT_AR),
        ("Krunal Pandya", P.CAT_AR),
        ("Deepak Hooda", P.CAT_BAT),
        ("Ayush Badoni", P.CAT_BAT),
        ("Mohsin Khan", P.CAT_BOWL),
        ("Ravi Bishnoi", P.CAT_BOWL),
        ("Naveen-ul-Haq", P.CAT_BOWL),
        ("Yash Thakur", P.CAT_BOWL),
        ("Shivam Mavi", P.CAT_BOWL),
        ("Manimaran Siddharth", P.CAT_BOWL),
        ("Mayank Yadav", P.CAT_BOWL),
        ("Amit Mishra", P.CAT_BOWL),
        ("Kyle Mayers", P.CAT_AR),
        ("Devdutt Padikkal", P.CAT_BAT),
        ("Ashton Turner", P.CAT_BAT),
        ("Arshad Khan", P.CAT_AR),
        ("Yudhvir Charak", P.CAT_AR),
        ("Prerak Mankad", P.CAT_AR),
        # Gujarat Titans
        ("Shubman Gill", P.CAT_BAT),
        ("David Miller", P.CAT_BAT),
        ("Sai Sudharsan", P.CAT_BAT),
        ("Matthew Wade", P.CAT_WK),
        ("Wriddhiman Saha", P.CAT_WK),
        ("Kane Williamson", P.CAT_BAT),
        ("Rashid Khan", P.CAT_AR),
        ("Rahul Tewatia", P.CAT_AR),
        ("Mohit Sharma", P.CAT_BOWL),
        ("Mohammed Shami", P.CAT_BOWL),
        ("Spencer Johnson", P.CAT_BOWL),
        ("Noor Ahmad", P.CAT_BOWL),
        ("Joshua Little", P.CAT_BOWL),
        ("Sandeep Warrier", P.CAT_BOWL),
        ("Darshan Nalkande", P.CAT_BOWL),
        ("Umesh Yadav", P.CAT_BOWL),
        ("Shahrukh Khan", P.CAT_BAT),
        ("Abhinav Manohar", P.CAT_BAT),
        ("Azmatullah Omarzai", P.CAT_AR),
        ("Kartik Tyagi", P.CAT_BOWL),
        ("Sushant Mishra", P.CAT_BOWL),
        ("Manav Suthar", P.CAT_BAT),
    ]

    seen: set[str] = set()
    out: list[dict[str, str]] = []
    for name, cat in raw:
        if name in seen:
            continue
        seen.add(name)
        out.append({"name": name, "category": cat})
    return out
