# Generated by Django 6.0.2 on 2026-03-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=100)),
                ('team_home', models.CharField(blank=True, default='', max_length=100)),
                ('team_away', models.CharField(blank=True, default='', max_length=100)),
                ('home_score', models.CharField(blank=True, default='', max_length=50)),
                ('away_score', models.CharField(blank=True, default='', max_length=50)),
                ('is_live', models.BooleanField(default=True)),
                ('scorecard_data', models.JSONField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
