# Generated by Django 6.0.2 on 2026-03-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livematch',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
