# Generated by Django 6.0.3 on 2026-04-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0003_livematch_uses_ipl_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livematch',
            name='uses_ipl_api',
            field=models.BooleanField(default=False, help_text='Scorecard/currentMatches for this match use the IPL CricAPI key.'),
        ),
    ]
